### PR TITLE
Bar charts must have colours if they have series

### PR DESCRIPTION
**Pull request by vitorbaptista**
For example, a stacked bar chart must have a different colour for each stacked
bar, otherwise the stack is visually identical to a single bar.

Before and after this change

### CODE REVIEW

**Comment by vitorbaptista** [comment]
For some reason, Travis isn't able to get this branch's commits. It's instead getting another commit, which fails for lint reasons. It's very likely that it's a bug in Travis itself, so we can safely ignore it IMHO.

**Comment by akariv** [comment]
@vitorbaptista @brew should this be merged?

**Comment by brew** [comment]
I did a little related work on the bar chart a few weeks ago, so it'll be worth checking out this behaves well with it. I'll have a look today.

**Comment by brew** [comment]
I believe this has been fixed in babbage.ui as part of https://github.com/openspending/openspending/issues/1200. e.g. [example moldova view](https://openspending.org/viewer/boost:boost-moldova-2005-2014?measure=%22adjusted.sum%22&groups%5B%5D=%22administrative_classification_2.admin1%22&series%5B%5D=%22date_2.year%22&order=%22adjusted.sum%7Cdesc%22&visualizations%5B%5D=%22BarChart%22&lang=en). 

@vitorbaptista given we used different approaches (I was trying to fix stacked category colours), can you take a quick look at the commit (https://github.com/openspending/babbage.ui/commit/143af944b95ec48c5731304a5327bbd9f8c3d0f3). If you're happy, you can close this without merging, and close https://github.com/openspending/openspending/issues/1200 too.

**Comment by vitorbaptista** [comment]
@brew I tested out and everything seems fine in production. I'm not sure if there are unwanted side effects to your commit (e.g. the previous code was different if `chartType == 'bar'`) and I didn't dig deeper on it.

However, as things seem to be working in production, I'm happy to have this closed :+1:

**Pull request closed without merging**
