### PR TITLE
Add GA code

### PR DESCRIPTION
**Pull request by kravets-levko**
okfn/os-private-issues/issues/43

### CODE REVIEW

**Comment by exmatrikulator** [comment]
I would prefer to use Piwik

**Comment by akariv** [comment]
@kravets-levko, @exmatrikulator has a point.

Can we make the GA JS snippet only enabled by an environment variable, so that other users of our code don't accidentaly report stuff to Google (and don't share our GA code)

@exmatrikulator: We must collect analytics, as this is one way for us to show our impact to our funders. Generally speaking we prefer to use cloud services whenever possible instead of maintaining and managing these non-core services in-house.

cc: @pwalsh

**Comment by kravets-levko** [comment]
Makes sense. I'll sink for a solution that will look good for all OS projects, and then update PRs.

**Comment by pwalsh** [comment]
@akariv @kravets-levko @exmatrikulator 

An env var to set "analytics snippet" with a name `ga` or other (if someone makes a PR for other snippets), and an env var for analytics identifier (injected into the snippet), can support ga and piwik easily. We should do that.

@exmatrikulator I'm a very big fan of Piwik, and I've used it quite extensively. However, for many, many years Open Knowledge International has used Google Analytics across all our work, and I don't see this changing anytime soon.

**Comment by exmatrikulator** [comment]
to bad ;(
and whats about the cloud service?
https://cloud.piwik.pro/pricing/

**Comment by pwalsh** [comment]
Hi @exmatrikulator it is quite a significant move for a non-profit to migrate ~100 web properties from an existing solution that works, to a new one that costs more. So, no, we will not be doing that in the foreseeable future.

**Pull request merged**
